name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Crear archivo PEM
      run: |
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Conectar por SSH y hacer deploy
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_URL }} << 'EOF'
          sudo docker rm -f super-mario-app || true
          sudo docker rmi -f super-mario-app || true
          cd ~/app || mkdir ~/app && cd ~/app
          git clone https://github.com/${{ github.repository }} repo || true
          cd repo
          git pull origin main
          cd backend
          sudo docker build -t super-mario-app .
          sudo docker run -d -p 3000:80 --name super-mario-app super-mario-app
        EOF